apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: python-fun
spec:
  tag: mcnichol/python-fun
  serviceAccount: kpack-demo-sa
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/mcnichol/python-math-fun
      revision: master
