apiVersion: v1
kind: Secret
metadata:
  name: kpack-demo-secret
  annotations:
    build.pivotal.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: mcnichol
